### ISSUE TITLE
List of dependencies to compile in Linux?

### ISSUE THREAD

**Issue by emdio** [amchess/ShashChess#10]
I'm trying to compile ShashChess in a Linux machine, and the lack of info on dependencies is making it a bit harder than it should be.

I solved the first issue by installing libcurl4-gnutls-dev, but now I get a new one ("/usr/bin/ld: cannot find -lws2_32").

So maybe it'd be a good idea to add library dependencies to the README file.

**Comment by amchess** [comment]
You have to eliminate "-lws2_32" in MakeFile because it's only for window

**Comment by emdio** [comment]
Nice, that did the trick.
