### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Rakicc** [amchess/ShashChess#11]
How to build for Android uaing mingw/msys2?

**Comment by MisesEnForce** [comment]
On my side, the android bin from https://github.com/amchess/ShashChess/releases/download/9.0/Android.7z does not work on my android phone. (SM-G975F, ARMv8-A, exynos9820, isntr set amr64-v8a)
Therefore, I would be very interested to how how to build ShashChess for android

**Comment by amchess** [comment]
We wait for a response from an Android system expert.

**Comment by rconstant42** [comment]
Hi, an android compilation made by hagtorp is in outskirts forum : https://app.box.com/s/zx5ess716pfwwt3tq952h1nksl2e5930
