### ISSUE TITLE
Shashchess 14 :- Linux

### ISSUE THREAD

**Issue by Arunachala-Ramana** [amchess/ShashChess#16]
Hello,

When will you upload the Linux version for Shashchess 14? Thanks for such engines :) Very grateful. Also i am not able to run ShashChess 13.2. Not sure what the problem is, but when i run with pychess, it says failed to run engine.

**Comment by tissatussa** [comment]
I also use Linux and i compiled ShashChess 15.1 succesfully .. i don't know about v13.2 and v14 .. remember to use a proper ARCHitecture for your PC when doing 'make' to compile. And what does the log show when you execute in terminal ?
