### ISSUE TITLE
Macintosh compile by Dariusz of ShashChess 2.0

### ISSUE THREAD

**Issue by yellow-panther** [amchess/ShashChess#2]
Hello amchess,
can you host this mentioned above build https://drive.google.com/drive/folders/0B5Ao6h_yMCl6ay04RjVtUDVTUG8  on https://github.com/amchess/ShashChess/releases too?

The lifetime of a file on Zippyshare expires only 30 days after the last download.

**Comment by amchess** [comment]
Yes, of course.
I did this:
[https://github.com/amchess/ShashChess/releases/tag/v2.0](url)
