### ISSUE TITLE
Error by compiling MacOS

### ISSUE THREAD

**Issue by ArminHHJ** [amchess/ShashChess#20]
Intel Mac, Catalina 10.15.7

use this command
make profile-build ARCH=x86-64-bmi2 COMP=clang
strip shashchess
mv 'shashchess' 'ShashChess17-x86-64-bmi2'
make clean

Get one Error:
ld: library not found for -lws2_32
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [shashchess] Error 1
make: *** [build] Error 2

=> file not build

Get also four warnings

montecarlo.cpp:68:14: warning: unused variable 'REWARD_MATE' [-Wunused-const-variable]
const Reward REWARD_MATE  = Reward(1.0);
             ^
In file included from montecarlo.cpp:30:
./montecarlo.h:110:10: warning: private field 'max_epsilon' is not used [-Wunused-private-field]
  double max_epsilon = 0.99;
         ^
./montecarlo.h:111:10: warning: private field 'min_epsilon' is not used [-Wunused-private-field]
  double min_epsilon = 0.00;
         ^
./montecarlo.h:112:10: warning: private field 'decay_rate' is not used [-Wunused-private-field]
  double decay_rate = 0.8;
         ^
4 warnings generated.

**Comment by amchess** [comment]
you have to remove the flag -lws2_32.
The warnings are normal.

**Comment by magicianofriga** [comment]
Hi,
I am facing the same problem on Linux. How do we remove this flag?

**Comment by amchess** [comment]
Simply on the Makefile
