### ISSUE TITLE
Creating experience for Shashchess and strength of MCTS compared to A/B NNUE.

### ISSUE THREAD

**Issue by magicianofriga** [amchess/ShashChess#21]
Hi, 
I was wondering about creating my own experience file for ShashChess. How does one do this?
Another question is regarding MCTS. How strong is MCTS compared to regular ShashChess? Also, what is the ideal number of full depth threads compared to regular ones?
Thank you!

**Comment by amchess** [comment]
you can surely  create an experience with mcts. MCTS has two version:
- Single using only main thread 
- Multi the opposite using all but main thread
The first one is stronger than the second one, but the quality of this last is better at longer time controls.
At not so fast time controls and with a good HW, Single is comparable in strength to classical alpha beta.

**Comment by magicianofriga** [comment]
Hi,
I play correspondence chess, so I use Shash Chess and BrainLearn mostly for hours on a Laptop i7(9750-h), with all the 12 threads. Is it possible for you to recommend a configuration for this that might maximise chances of winning games?

So using MCTS makes ShashChess weaker than regular engines like Stockfish? What will be the value add of using MCTS then? My considerations are mostly hours of deep analysis.
