### ISSUE TITLE
Experience Files not merging

### ISSUE THREAD

**Issue by magicianofriga** [amchess/ShashChess#22]
Hi,
What would be the names of the experience files to merge them?
I currently have experience.bin and experience1.bin. With this when I load the engine in Chessbase it doesn't merge the experiences. What is the solution? Thanks!

**Comment by amchess** [comment]
The correct naming is experience.bin, experience0.bin, experience1.bin..., but it's easier to use BrainLearn for this, because it has learning by default.

**Comment by magicianofriga** [comment]
Oh ok sure. Thanks!
