### ISSUE TITLE
Random zobrist-keys

### ISSUE THREAD

**Issue by Luecx** [amchess/ShashChess#24]
I stumbled across this SF-Fork and am i kinda interested in why you wrote down all the random zobrist keys by hand? I mean it must have been proven to be better than a simple call to some random function inside a loop. Do you have any proof for that? It's really interesting since I was also thinking about some better way to distribute the zobrist keys to reduce collisions-

**Comment by amchess** [comment]
No random keys are crucial for learning mechanism.
