### ISSUE TITLE
Compile problems on 32 bit ARMv7 Raspberry Pi 4

### ISSUE THREAD

**Issue by ScallyBag** [amchess/ShashChess#26]
Hi,

When I try to compile your Engine I get this error:

search.cpp:44:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [<builtin>: search.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/Al/Engine-Source/shashChess/src/All'
make[1]: *** [Makefile:893: gcc-profile-make] Error 2
make[1]: Leaving directory '/home/Al/Engine-Source/shashChess/src/All'
make: *** [Makefile:751: profile-build] Error 2
Al@RPi4-SSD:~/Engine-Source/shashChess/src/All $ 

What I can I do to avoid this error?

Thanks,

Al.

**Comment by amchess** [comment]
You have to install curl library, but I'm not so expert about raspberry

**Comment by ScallyBag** [comment]
Thanks,

That works 👍

Al
