### ISSUE TITLE
fatal error: curl/curl.h: No such file or directory - Compile on Windows mingw64

### ISSUE THREAD

**Issue by bitsocket** [amchess/ShashChess#27]
cd ShashChess/src/All
make build ARCH=x86-64-bmi2 COMP=gcc COMPCXX=g++

search.cpp:44:10: fatal error: curl/curl.h: No such file or directory
   44 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~

The include file 'curl.h' is missing.

**Comment by RapidGames2** [comment]
i have the same problem. Can you help me plz ? thanks

**Comment by amchess** [comment]
You have to download the curl library and put it in the mingw compiler

**Comment by RapidGames2** [comment]
Link for download please ? thanks

**Comment by amchess** [comment]
https://www.dropbox.com/s/aiqlfhlqvvzt4z5/mingw6432version10.2.7z?dl=0

Use it: there is all to build. Follow the readme.

**Comment by RapidGames2** [comment]
Thank you very much. Solved

**Comment by RapidGames2** [comment]
Small request: can you do the same thing and on gcc 11.2 please? thanks
