### ISSUE TITLE
No checkbox for turning off 50-move draw rule in TB endings:

### ISSUE THREAD

**Issue by Firebrandx** [amchess/ShashChess#29]
Stockfish has a setting quite valuable to ICCF players: Uncheck 50-move draw rule in endgame TB's. ICCF removed such draw rules so the endgame TB can force checkmates that would normally have violated this outdated OTB rule. 

I was looking for this same checkbox in ShashChess, and couldn't find it.

**Comment by amchess** [comment]
I eliminated because rarely used. I can reintroduce in the next version.

**Comment by Firebrandx** [comment]
That seems odd because the credits for Shashchess include some ICCF players. I would hope they stressed the importance of including ICCF rule options in the parameters like the aforementioned 50-move-draw rule override for TBs.

At any rate, yes please include it as a parameter. Thanks!

**Comment by Firebrandx** [comment]
Thanks for the new release adding this feature!

**Comment by amchess** [comment]
you're welcome
