### ISSUE TITLE
Trying to compile program

### ISSUE THREAD

**Issue by bowlb** [amchess/ShashChess#30]
Hello, I have imported the code into Visual Studio and am trying to run the program.  Which file do I run?  Is it one of the Makefiles?  I always get an error "Please select a valid startup item".  Do I need to create a project first?

I apologize for my extremely basic questions as I don't have a strong background in coding.  Am attempting to explore the applications of Shashin's methods to over the board thinking as I am a big fan of his book.  

Thanks, Daren

**Comment by amchess** [comment]
You have to run the solution in Visual Studio: no MakeFile
