### ISSUE TITLE
Feature: Command to "count" all piece moves, and delta(move)

### ISSUE THREAD

**Issue by HerbM** [amchess/ShashChess#31]
I am trying to study the book which presumably you folks have already done.

Although embarrassed to admit it, I'm still making mistakes counting and want to practice with a tool that will give me immediate feedback.

Anything out there like this for Coach Shashin's parameters?

**Also:  Anyone have contact info for Alexander Shashin?**

I'd like to pursue (online) lessons with him. 

He's still listed as a coach with GMChess.com (aka GrandMaster Chess, but non one seems to be answering their contact email and many of their internal site links are dead.

**Comment by amchess** [comment]
Unfortunately, I have no direct contact with Alexander Shashin.
I have simply studied his book.
I think it is very useful for analyzing matches/positions and improving positional sensitivity.
In OTB practice, though, the mathematical formulas given are inapplicable and should be taken as guidelines.

**Comment by HerbM** [comment]
Thx for taking the time to answer.  If you would rather just send email or something we can close this "issue".

> ...I have simply studied his book. 

I'm only about a third of the way through, most of Part 1.

> I think it is very useful for analyzing matches/positions and improving positional sensitivity. 

Do you believe it is essentially correct enough to be useful?

> In OTB practice, though, the mathematical formulas given are inapplicable and should be taken as guidelines.

If it's not practical OTB (standard time controls), is this due to being too inaccurate or to being impractical to count and calculate, or something else?

I presume you have found it somewhat effective or would not have devoted time to building this project.

Did you include any functions to query the engine for the calculated parameters?

**Comment by HerbM** [comment]
BTW, do you have any idea why it is delta(move) and not just a simple delta-parameter name?

At first I thought maybe Shashin intended to calculate this after project your next move but don't see evidence of that in his calculations.

**Comment by amchess** [comment]
It's not practical OTB to count and calculate.
I adapted Shashin theory for Stockfish.
delta(move) means the delta between all white and black moves.
