### ISSUE TITLE
Could you correct my name in Read.me file?

### ISSUE THREAD

**Issue by Galaxy-Wizard** [amchess/ShashChess#33]
Hello, Andrea!
How do you do?
Could you write you phone to deal with telegram application and mail?
Here are my contacts:
kozlov_sergey_aleksandrovitsch@mail.ru https://galaxy.group.keenetic.link/

Andrea, please write this way "Kozlov Sergey Aleksandrovitsch".
I just realized, that my fathers name should be written such way.

**Comment by amchess** [comment]
Done
