### ISSUE TITLE
Android version not working under Android 11

### ISSUE THREAD

**Issue by rafv58** [amchess/ShashChess#34]
The ARM8 version does not work with Android 11 in realme UI V2.0. Hardware MT6785V/CD
6 cortex-A55, 2 cortex-A76

**Comment by amchess** [comment]
Ask Archimedes on outskirts forum. I'm not an android expert.

**Comment by rafv58** [comment]
No problem. I can wait for newer Versions till It works.
Is not priority for you and its not priority for me.

**Comment by amchess** [comment]
Solved
