### ISSUE TITLE
Version 26 don't work in Android.

### ISSUE THREAD

**Issue by Ctraf22** [amchess/ShashChess#36]
Android 12

**Comment by amchess** [comment]
I'm not an Android expert.
I'll ask.

**Comment by amchess** [comment]
There are two variants, one compiled with GCC (the fastest builds) and the other with android ndk (without live book). Have you tested both variants? Give us more infos please.

**Comment by archimedeschess** [comment]
Try the version without live book. You know how to deal with a non-embedded network? If not or your chess app doesn't support it (e.g. no uci options are offered for selecting the network), there is also an embedded version available.
