### ISSUE TITLE
Question to shashchess author

### ISSUE THREAD

**Issue by cj5716** [amchess/ShashChess#49]
If a patch passes the 10-games 25 min + 10 second test and the test suite, however it fails the short time control SPRT in stockfish, will it be merged (considering shashchess author prioritises longer time controls?)

**Comment by amchess** [comment]
Clearly, completely random games, especially with nnue, imho, are useless

**Comment by amchess** [comment]
If you need more infos and are interested in collaborating, you can contact me in private

**Comment by cj5716** [comment]
Thank you, I was just interested in your testing methodology. Good luck!
