### ISSUE TITLE
MCTS Developing

### ISSUE THREAD

**Issue by VezirChess** [amchess/ShashChess#5]
Hello!
First, congrats! You did a great job with ShashChess. This is the greatest chess engine I had ever see.
But you can improve it. The MCTS mode is not good enough. It is giving wrong evaluation because of wrong variants (Generally it sees wrong sacrifices.)
Also, I want you to look the Scorpio Chess Engine (https://github.com/dshawul/Scorpio) 's MCTS for improve ShashChess's MCTS.
Except these, ShashChess is a super chess engine..
Thank you..

**Comment by amchess** [comment]
Hi.
Thanks for your advise.
You're right: mcts is experimental and the goal is just to improve it
If you want collaborate, you can contact me in private:
amchess@libero.it
Best regards,
Andrea

**Comment by VezirChess** [comment]
Well, I don't know Computers' Language, but you can maybe set 2 buttons for MCTS:
1-use MCTS
2-use Self-Learning

**Comment by VezirChess** [comment]
And you can improve MCTS play style.
