### ISSUE TITLE
‏‏

### ISSUE THREAD

**Issue by WampServer** [amchess/ShashChess#53]
@amchess _Please delete this issue._

**Comment by WampServer** [comment]
I did bring this up on the CCRL forum.

https://biokirr.com/Chess/CCRL-Forum/viewtopic.php?p=140765

**Comment by WampServer** [comment]
@amchess Hi Andrea, Unfortunately Stockfish community are got no manners - they're rude to everyone. I tried my best to support you but they wouldn't allow it and finally I have been banned from Official_Stockfish. [official-stockfish#5156](https://github.com/official-stockfish/Stockfish/issues/5156) , [official-stockfish#5157](https://github.com/official-stockfish/Stockfish/issues/5157) 

One of the things that has amazed me is that many of them prefer to be rude with other people. I appreciate you for this sentence:

> _I develop a fork of stockfish with the goal of making it understandable/useful to the OTB player, not necessarily, therefore, stronger, and I wondered why this frightening degradation of performance.  That's all._
> 
> _Originally posted by @amchess in https://github.com/official-stockfish/Stockfish/issues/5157#issuecomment-2041459278_

If you are interested, I would like to cooperate with you so that we can build a powerful engine. I also wanted to say thanks for your hard work. 

Regards,
Fisherman

**Comment by WampServer** [comment]
I also commented a game to prove your point but it was removed.

```
[Event "Bullet game"]
[Date "2024.04.07"]
[White "Stockfish 16"]
[Black "Stockfish 16.1"]
[Result "1-0"]
[Variant "Standard"]
[TimeControl "120+1"]
[ECO "D11"]
[Opening "Slav Defense: Modern Line"]

1. d4 d5 2. c4 c6 3. Nf3 { D11 Slav Defense: Modern Line } dxc4 4. e3 b5 5. a4 e6 6. axb5 cxb5 7. b3 Nf6 8. bxc4 bxc4 9. Bxc4 Bb7 10. O-O Be7 11. Qb3 Bxf3 12. gxf3 O-O 13. Bd2 Nbd7 14. Ba5 Nb6 15. Nd2 Bd6 16. Rfc1 Rc8 17. f4 g6 18. Qb5 Kg7 19. h3 Qe7 20. Bxb6 axb6 21. Qxb6 Bb4 22. Nf3 Ba3 23. Rc2 Rb8 24. Qa5 Bb4 25. Qa2 Ra8 26. Qb1 Bd6 27. Bf1 Rfb8 28. Qc1 Rxa1 29. Qxa1 Rb7 30. Ne5 Ra7 31. Qe1 Qd8 32. Bg2 Qb6 33. Qc3 Rc7 34. Rb2 Qa6 35. Qb3 Nd7 36. Nd3 Qa3 37. Qb5 Nf6 38. Bf3 Rc8 39. Qb3 Rc3 40. Qxa3 Bxa3 41. Rd2 Nd7 42. Be2 Rc7 43. Kg2 Be7 44. Rb2 Bd8 45. Bd1 Rc3 46. Be2 Rc7 47. Ne1 Nf6 48. Nf3 Ne4 49. Ba6 Nd6 50. Ne5 Bh4 51. Bd3 Nc8 52. Rb5 Ra7 53. Rc5 Nb6 54. Rc2 Nd5 55. Kf3 Rc7 56. Rb2 Bf6 57. Rb1 Ne7 58. Kg3 Nc6 59. Be4 Ne7 60. Rb8 Nc8 61. Ra8 Be7 62. Bf3 Bd6 63. Kg2 Be7 64. Ra6 Bd6 65. Ra8 Nb6 66. Ra5 Nc8 67. Rb5 Ne7 68. Rb6 Nc8 69. Rb8 Ne7 70. Rb6 Nc8 71. Rb8 Ne7 72. Ra8 Nc8 73. Be4 Bf8 74. Kf3 Bd6 75. Ke2 Be7 76. Ra6 Ra7 77. Rc6 Nd6 78. Bd3 Bf8 79. Kf3 Ne8 80. Rc8 Nd6 81. Rb8 Rc7 82. h4 h5 83. Rb1 Nc8 84. Rg1 Ne7 85. Ke2 Rc8 86. Ra1 Rc7 87. Be4 Nc8 88. Rg1 Ne7 89. Bd3 Kf6 90. Ra1 Nc6 91. Nf3 Kg7 92. Ra6 Nb4 93. Ra1 Nd5 94. Ng5 Be7 95. Kf3 Bf6 96. Be4 Ne7 97. Ra5 Rd7 98. Kg2 Kg8 99. Kg3 Kg7 100. Kh3 Ng8 101. Ra6 Ne7 102. Bg2 Nf5 103. Bh1 Rc7 104. Bc6 Be7 105. d5 exd5 106. Bxd5 Bf6 107. Be4 Nh6 108. Kg2 Re7 109. Bb1 Rb7 110. Ba2 Bc3 111. Bd5 Rd7 112. Be4 Bf6 113. Ra5 Re7 114. Kf3 Rd7 115. Kg2 Re7 116. Ra4 Rd7 117. Kg3 Bc3 118. Ra3 Be1 119. Nf3 Bb4 120. Ra6 Re7 121. Bd3 Rc7 122. Ne5 Bc3 123. Kg2 Bxe5 124. fxe5 Rc3 125. Bb1 Rb3 126. Ba2 Rb4 127. Ra7 Kf8 128. Ra8+ Kg7 129. Ra7 Kf8 130. f4 Rb2+ 131. Kg3 Re2 132. Ra3 Nf5+ 133. Kf3 Rh2 134. Ra8+ Kg7 135. Ra7 Rh3+ 136. Kf2 Rh2+ 137. Kg1 Rd2 138. e6 Nxh4 139. Bd5 Rxd5 140. Rd7 Nf3+ 141. Kf2 Ng5 142. Rxd5 Nxe6 143. Re5 Nf8 144. Re7 Ne6 145. Kf3 g5 146. Rd7 Kg6 147. Rd6 h4 148. Kg4 f5+ 149. Kh3 Kf7 150. fxg5 Nxg5+ 151. Kxh4 Ne6 152. Kg3 Kf6 153. Kf3 Ke5 154. Ra6 Ng5+ 155. Ke2 Ne6 156. Ra5+ Ke4 157. Ra4+ Ke5 158. Ra5+ Ke4 159. Ra7 Ng5 160. Ra4+ Ke5 161. Ra5+ Ke4 162. Ra1 Ne6 163. Ra5 Ng5 164. Ra6 Ke5 165. Kd3 Nf3 166. Ra5+ Ke6 167. Ra6+ Kd5 168. Rb6 Ne5+ 169. Ke2 Ke4 170. Rb4+ Kd5 171. Ra4 Ke6 172. Ra6+ Kd5 173. Kf2 Nd3+ 174. Kf3 Ke5 175. Rb6 Kd5 176. Rb3 Kc4 177. Ra3 Ne1+ 178. Ke2 Kb4 179. Ra7 Nc2 180. Rf7 Kb5 181. Rxf5+ Kc6 182. Kf3 Na3 183. Ke4 Nc2 184. Kf3 Nb4 185. Ra5 Nc2 186. Ke4 Kb6 187. Ra2 Nb4 188. Rb2 Kc5 189. Rxb4 Kxb4 190. Kd5 Kb5 191. e4 Kb6 192. Ke6 Kc5 193. e5 Kd4 194. Kd6 Ke4 195. e6 Kd4 196. e7 Kc4 197. e8=Q Kd3 198. Kd5 Kd2 199. Kc4 Kc2 200. Qe2+ Kb1 201. Kc3 Ka1 202. Qb2# 1-0
```

**Comment by WampServer** [comment]
Please delete this issue

**Comment by WampServer** [comment]
@amchess Please delete this issue.

**Comment by EarlyEdition** [comment]
@amchess, Thank you for the good times, true friendship and unforgettable memories of the past year.

- https://github.com/official-stockfish/Stockfish/issues/5156

- https://github.com/official-stockfish/Stockfish/issues/5157

I'd never expected you to remove me from my organization, and I had to decide what to do. 

As my last request, I ask you transfer my repository: https://github.com/Stockfish-NNUE/Stockfish

Good Luck!
