### ISSUE TITLE
It's not possible to switch the net

### ISSUE THREAD

**Issue by Chess321** [amchess/ShashChess#55]
### Describe the issue

It's not possible to use updated NNUE architecture SFNNv9 and net nn-ae6a388e4a1a.nnue

### Expected behavior

Use the new and very big 3072 size net nn-ae6a388e4a1a.nnue

### Steps to reproduce

https://abrok.eu/stockfish/
https://tests.stockfishchess.org/nns

### Operating system

Linux

### ShashChess version

ShashChess 35

**Comment by amchess** [comment]
It's normal: you have to change the related code.
