### ISSUE TITLE
ShashChess is not update on CCRL ranking list

### ISSUE THREAD

**Issue by EarlyEdition** [amchess/ShashChess#57]
### Describe the issue

Hi Andrea,

We have 4 releases after ShashChess GZ:
1. ShashChess 35
2. ShashChess 34
3. ShashChess 33
4. ShashChess 32
5. ShashChess GZ

And this lack of updating brings the `ShashChess GZ` version lower in the ranking list.

### Expected behavior

ShashChess 35 is expected to be on the ranking list.

### Steps to reproduce

https://computerchess.org.uk/ccrl/4040/

### Operating system

All

### ShashChess version

ShashChess 35

**Comment by amchess** [comment]
I don't know.

**Comment by EarlyEdition** [comment]
Therefore, I humbly request @SzotsGabor to explain this issue.

**Comment by EarlyEdition** [comment]
@amchess CCRL ranking is always correct. Probably a regression must have happened after **ShashChess (GZ)**.

**Comment by amchess** [comment]
I talked to Graham.
He told me that he had queued up the ShashChess test.

**Comment by EarlyEdition** [comment]
Can **ShashChess** regain his number 1 ranking in the world after almost a year?

**Comment by EarlyEdition** [comment]
> I talked to Graham.
> He told me that he had queued up the ShashChess test.

Thanks Andrea for the tip. I also wanna register my new engine for CCRL ranking. How can I talk to @GrahamCCRL?

**Comment by EarlyEdition** [comment]
@GrahamCCRL Are you here?

**Comment by EarlyEdition** [comment]
I wanna register my new engine for CCRL ranking. I try to register neither surprise nor dismay. Please guide me in finding ways to register my engine and determination the best way possible.

**Comment by EarlyEdition** [comment]
@GrahamCCRL, Please see the comments below to understand my opinion.
> _Originally posted  in https://github.com/official-stockfish/Stockfish/discussions/4678#discussioncomment-9887796_

I just said: '_Thanks to @amchess for developing the chess engine ❤️_'

@official-stockfish admins hid my comment. Isn't that disrespectful treatment?

It's hard to compete. I wanna register my engine for CCRL ranking.

**Comment by EarlyEdition** [comment]
@GrahamCCRL I know with certainty there is no chance that my engine will register for CCRL ranking.
So I have a small request - could you please star my repository? https://github.com/HalfKP/NNUE

**Comment by EarlyEdition** [comment]
@GrahamCCRL, I thank you for starring my repository. Today, I realized that you unstar my repo. 
But what is the reason for that? Was it because of this post? https://github.com/official-stockfish/Stockfish/pull/5482#issuecomment-2227202084

**Comment by EarlyEdition** [comment]
Hi @amchess, 
I've created a new account. Please invite me to @stockfish-nnue. Please select my role in the organization as **owner**.

![h3Dsv](https://github.com/user-attachments/assets/77713138-da7e-4e14-a0a3-886da3dab499)

Thanks!

**Comment by KasparovChess** [comment]
@amchess, If you want to set someone as an admin for the entire organization:

1. Navigate to the Organization > People
<img src="https://i.sstatic.net/hMdM5.png" alt="org > people">

2. Identify the member you want to update and click on the settings cog
<img src="https://i.sstatic.net/GTGra.png" alt="settings > change role">

3. Set role to `Owner`
<img src="https://i.sstatic.net/xYZHq.png" alt="Select Role">

**Comment by EarlyEdition** [comment]
@amchess, Please delete my organization. Thanks!
