### ISSUE TITLE
Great work!  How can I help?

### ISSUE THREAD

**Issue by bahmanm** [amchess/ShashChess#60]
### Describe the issue

I use ShashChess on a daily basis to analyse games and play matches. It has become my go-to engine for literally anything chess :sunglasses: 

This is a fantastic chess engine and I thank you for your efforts.

Is there any way I could contribute to ShashChess? What are the areas that you'd need an extra hand with?

I'm a software engineer myself and can find my way around a C++ codebase but I am so far from engine theory and in particular Shashin's.

On a related note, is there a way to financially support your work?

Keep up the great work :muscle: 

### Expected behavior

N/A

### Steps to reproduce

N/A

### Operating system

Linux

### ShashChess version

35.3

**Comment by amchess** [comment]
Sure. You can contact me in private, for example, skype: oznamaerdna

**Comment by bahmanm** [comment]
Is there any other medium that could work you? I'm having trouble running Skype on my laptop and phone :sweat_smile: Here's my e-mail: Bahman@BahmanM.com. Please drop me a line if you could and we can take it from there :pray:
