### ISSUE TITLE
Can you detail what this is private application and how to get it?

### ISSUE THREAD

**Issue by aochoam** [amchess/ShashChess#9]
Hello, 

Please, can you provide more details on how to get the private offline learning application?
"Not having it, the default performance is 0 (not applied)"

Thank you.
Arturo Ochoa.

**Comment by amchess** [comment]
As explained in the ReadME, the application is private. 
So it isn't available and its goal is to fill the performance parameter based on positional patterns.

**Comment by aochoam** [comment]
Ok thanks.

Sorry, I could not do it.
 I tried to follow the instructions. 

"At the engine loading, there is an automatic merge to experience.bin files, if we put the other ones, based on the following convention:
<fileType><qualityIndex>.bin
where
fileType="experience"/"bin"
qualityIndex , an integer, incrementally from 0 on based on the file's quality assigned by the user (0 best quality and so on)
N.B._

I have some questions:
- filetype convention in windows is bin2.bin?
- Do I have to locate the final in a separated folder such experience/bin and then the files.

Thank you,
Arturo Ochoa.

**Comment by amchess** [comment]
No.
The files are in the same engine's folder and are named like this
experience.bin
experience0.bin
experience1.bin
and so on
to be merged

experience0.bin is the file with the highest priority in merging.

**Comment by aochoam** [comment]
Hello,

Thank you so much. It worked like a charm.

Kind regards, Arturo Ochoa.
